language: ruby
script: 'true'
rvm:
 - 2.6.0
addons:
  postgresql: 9.6
before_script:
  - psql -c 'create database rails-girls-events_test;' -U postgres
script:
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rspec
