addons:
  postgresql: 9.6
services:
  - postgresql
before_script:
  - psql -c 'create database rails-girls-events_test;' -U postgres
language: ruby
rvm:
 - 2.6.0
script:
 — bundle install — jobs=3 — retry=3
 — bundle exec rake db:create
 - bundle exec rake db:migrate RAILS_ENV=test
 - bundle exec rspec
  
